# -*- coding: utf-8 -*-
"""K-meanselbow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2t0S_DjFg9UpixnhgQd_yMq0IoFcQ2O
"""

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

df=pd.read_csv('/content/Mall_Customers.csv')
df.head()

print(df.info())
print(df.describe())

plt.scatter(df['Annual Income (k$)'],df['Spending Score (1-100)'])
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.show()

x=df[['Annual Income (k$)','Spending Score (1-100)']]
scalar=StandardScaler()
x_scaled=scalar.fit_transform(x)

k_mean=KMeans(n_clusters=5,random_state=42)
k_mean.fit(x_scaled)

wcss=[]
for i in range(1,11):
  kmean=KMeans(n_clusters=i,random_state=42)
  kmean.fit(x_scaled)
  wcss.append(kmean.inertia_)
print("Wcss value:",wcss)
plt.plot(range(1,11),wcss,marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

k_mean=KMeans(n_clusters=5,random_state=42)
df['Cluster']=k_mean.fit_predict(x_scaled)
df.head()

plt.figure(figsize=(8,6))
for cluster in range(5):
  plt.scatter(
     df[df['Cluster']==cluster]['Annual Income (k$)'],
     df[df['Cluster']==cluster]['Spending Score (1-100)'],
     label=f'Cluster {cluster}'
  )
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

import joblib
joblib.dump(scalar,'scalar.pkl')
joblib.dump(k_mean,'cluster_model.pkl')